version: 2
project_name: bkt

before:
  hooks:
    - go mod tidy

builds:
  - id: bkt
    main: ./cmd/bkt
    binary: bkt
    env:
      - CGO_ENABLED={{- if eq .Os "darwin" }}1{{- else }}0{{- end }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/avivsinai/bitbucket-cli/internal/build.versionFromLdflags={{.Version}}
      - -X github.com/avivsinai/bitbucket-cli/internal/build.commitFromLdflags={{.Commit}}
      - -X github.com/avivsinai/bitbucket-cli/internal/build.dateFromLdflags={{.Date}}
    mod_timestamp: '{{ .CommitDate }}'

archives:
  - id: bkt-archive
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ incpatch .Version }}-next+{{ .ShortCommit }}"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
  groups:
    - title: '🚀 Features'
      regexp: '^feat(\(.+\))?:'
      order: 0
    - title: '🐛 Bug Fixes'
      regexp: '^fix(\(.+\))?:'
      order: 1
    - title: '📦 Dependencies'
      regexp: '^deps(\(.+\))?:'
      order: 2
    - title: '🔧 Other Changes'
      order: 999

release:
  github:
    owner: avivsinai
    name: bitbucket-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## bkt {{ .Tag }} ({{ .Date }})

    Thanks for trying the Bitbucket CLI!
  footer: |
    ---

    **Full Changelog**: https://github.com/avivsinai/bitbucket-cli/compare/{{ .PreviousTag }}...{{ .Tag }}

    ### Go Install
    ```bash
    go install github.com/avivsinai/bitbucket-cli/cmd/bkt@{{ .Tag }}
    ```

    ### Binary Downloads
    Pick the archive for your platform from the assets below.

sboms:
  - id: syft-json
    artifacts: archive
    cmd: syft dir:${{dir}} -o cyclonedx-json={{ .Name }}.sbom.json

brews:
  - name: bkt
    tap:
      owner: avivsinai
      name: homebrew-tap
    folder: Formula
    description: Bitbucket CLI with gh-style ergonomics
    homepage: https://github.com/avivsinai/bitbucket-cli
    license: MIT
    test: |
      system "#{bin}/bkt", "--version"

nfpms:
  - id: deb
    package_name: bkt
    file_name_template: 'bkt_{{ .Version }}_{{ .Arch }}'
    formats: [deb]
    maintainer: Aviv Sinai <opensource@avivsinai.dev>
    description: Bitbucket CLI
    homepage: https://github.com/avivsinai/bitbucket-cli
    license: MIT
