#!/usr/bin/env bash
# check-generated-skill.sh — verify generated skill rules are up-to-date.
# Runs the docgen generator into a temp dir and diffs against the committed
# rules. Exits non-zero if there's drift.
set -euo pipefail

RULES_DIR="skills/bkt/rules"
SKILL_MD="skills/bkt/SKILL.md"

# Generate into a temp directory
TMPDIR="$(mktemp -d)"
trap 'rm -rf "$TMPDIR"' EXIT

# Copy SKILL.md so the generator can update its References section
cp "$SKILL_MD" "$TMPDIR/SKILL.md"
mkdir -p "$TMPDIR/rules"

go run ./cmd/docgen -o "$TMPDIR/rules" 2>/dev/null

# Compare rule files
if ! diff -rq "$RULES_DIR" "$TMPDIR/rules" >/dev/null 2>&1; then
    echo "❌ Generated skill rules are stale. Run 'make generate-skill' and commit the result."
    diff -rq "$RULES_DIR" "$TMPDIR/rules" || true
    exit 1
fi

# Compare the References section in SKILL.md
# Extract from the auto-generated marker to the end marker
extract_refs() {
    sed -n '/<!-- auto-generated by cmd\/docgen/,/<!-- end auto-generated -->/p' "$1"
}

COMMITTED_REFS="$(extract_refs "$SKILL_MD")"
GENERATED_REFS="$(extract_refs "$TMPDIR/SKILL.md")"

if [ "$COMMITTED_REFS" != "$GENERATED_REFS" ]; then
    echo "❌ SKILL.md References section is stale. Run 'make generate-skill' and commit the result."
    diff <(echo "$COMMITTED_REFS") <(echo "$GENERATED_REFS") || true
    exit 1
fi

echo "✓ Generated skill rules are up-to-date"
